name: Ruby

on:
  schedule:
    - cron:  '0 * * * *'
    - cron:  '20 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: run csv generate script
      run: |
        git remote add src https://github.com/CSSEGISandData/COVID-19.git
        git fetch src
        git merge -m 'merge data' src/master
        ruby parse_case.rb csse_covid_19_data/csse_covid_19_daily_reports/*.csv > converted_data/japan_cases.csv
        git commit -a -m 'update data'
        git push origin master

