name: Ruby

on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: git checkout master
      run: |
        git checkout master
    - name: git config
      run: |
        git config --global user.email "kameda.sbng@gmail.com"
        git config --global user.name "update csv"
    - name: git fetch
      run: |
        git remote add src https://github.com/CSSEGISandData/COVID-19.git
        git fetch src
    - name: git merge
      run: |
        git merge --allow-unrelated-histories -m 'merge data' src/master
    - name: run csv generate script
      run: |
        ruby parse_case.rb csse_covid_19_data/csse_covid_19_daily_reports/*.csv > converted_data/japan_cases.csv
    - name: git push
      run: |
        git commit -a -m 'update data'
        git push origin master
        
